### ISSUE TITLE
key.toggle problems

### ISSUE THREAD

**Issue by paulie-g** [paulie-g/autopy2#36]
<a href="https://github.com/nickehallgren"><img src="https://avatars1.githubusercontent.com/u/2547034?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nickehallgren](https://github.com/nickehallgren)**
_Saturday Jan 24, 2015 at 17:15 GMT_
_Originally opened as https://github.com/msanders/autopy/issues/65_

----

Hi,

I installed autopy on debian 7 using your instructions (compile from git)) and the Hello World example works but when I try to send CTRL + 1 I get an error, this is my code:

```
import autopy, time

def key_demo():
  autopy.key.toggle('1', True, autopy.key.MOD_CONTROL)
  time.sleep(2)
  autopy.key.toggle('1', False, autopy.key.MOD_CONTROL)  

def hello_there_world():
    autopy.alert.alert("Hello, world")

hello_there_world()
key_demo()
```

and the result is this:

Traceback (most recent call last):
  File "autopy_demo.py", line 12, in <module>
    key_demo()
  File "autopy_demo.py", line 4, in key_demo
    autopy.key.toggle('1', True, autopy.key.MOD_CONTROL)
TypeError: argument 1 must be integer<H> or char, not str

I'm pretty sure I have used the same code in another project so can this be that some library or something is missing?

**Comment by paulie-g** [comment]
<a href="https://github.com/carlpett"><img src="https://avatars1.githubusercontent.com/u/214867?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [carlpett](https://github.com/carlpett)**
_Monday Jan 26, 2015 at 11:59 GMT_

----

I have this problem as well. Somewhat surprisingly, it works if I cast to unicode first, which in your case would be 

```
def key_demo():
  autopy.key.toggle(u'1', True, autopy.key.MOD_CONTROL)
  time.sleep(2)
  autopy.key.toggle(u'1', False, autopy.key.MOD_CONTROL)  
```

I looked into the source (`autopy-key-module.c`, code excerpt below), and I'm guessing there might be a problem with `PyUnicode_Check`. I couldn't locate the source for that one, though (checked python source)

```
if (PyNumber_Check(key)) { /* Check for key code */
    MMKeyCode code;
    if (!MMKeyCodeFromPyInt(key, &code)) return NULL;
    toggleKeyCode(code, downBool == Py_True, flags);
} else if (PyUnicode_Check(key)) { /* Check for single-character string */
    char c;
    if (!charFromPyString(key, &c)) return NULL;
    toggleKey(c, downBool == Py_True, flags);
} else {
    return Py_SetArgConvertErr("integer<H> or char", 1, key);
}
```

**Comment by paulie-g** [comment]
<a href="https://github.com/raga70"><img src="https://avatars2.githubusercontent.com/u/8299535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [raga70](https://github.com/raga70)**
_Friday Aug 19, 2016 at 16:11 GMT_

----

how i can togle enter key

**Comment by paulie-g** [comment]
<a href="https://github.com/flufy3d"><img src="https://avatars1.githubusercontent.com/u/1730604?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [flufy3d](https://github.com/flufy3d)**
_Friday Sep 23, 2016 at 12:56 GMT_

----

Got an idea from #65. Cast numbers to long and it works.

key.toggle(long(key.K_DELETE), True)
