### ISSUE TITLE
remote operation with autopy

### ISSUE THREAD

**Issue by paulie-g** [paulie-g/autopy2#63]
<a href="https://github.com/davesliu"><img src="https://avatars3.githubusercontent.com/u/20762865?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [davesliu](https://github.com/davesliu)**
_Thursday Aug 31, 2017 at 06:38 GMT_
_Originally opened as https://github.com/msanders/autopy/issues/96_

----

I want to use autopy in a shell of a remote machine. It always pop out below errors. Can it support remote mouse & key operation with autopy?

>>> import autopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "autopy/__init__.py", line 9, in <module>
    import autopy.alert
ImportError: No module named alert
>>>

**Comment by paulie-g** [comment]
<a href="https://github.com/daluu"><img src="https://avatars1.githubusercontent.com/u/637306?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [daluu](https://github.com/daluu)**
_Sunday Sep 10, 2017 at 02:52 GMT_

----

How exactly are you running autopy in this setup? Some details would help.

On a related note, maybe this 3rd party project might help: https://github.com/daluu/autopydriverserver

**Comment by paulie-g** [comment]
<a href="https://github.com/davesliu"><img src="https://avatars3.githubusercontent.com/u/20762865?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davesliu](https://github.com/davesliu)**
_Tuesday Sep 12, 2017 at 14:34 GMT_

----

I can run the auotpy in a shell on desktop of Ubuntu OS. But if I tried to use  autospy in an shell on another machine to control the mouse movement of Ubuntun OS remotely, it will fail

**Comment by paulie-g** [comment]
<a href="https://github.com/daluu"><img src="https://avatars1.githubusercontent.com/u/637306?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [daluu](https://github.com/daluu)**
_Tuesday Sep 12, 2017 at 20:55 GMT_

----

My guess then is that AutoPy needs active desktop access, which running locally (if not in barebone terminal CLI mode only, e.g. fire up a shell window in Ubuntu desktop to run AutoPy) does provide.

But obviously whenever you run remotely, that access isn't there (it's a headless, CLI/terminal only session). You could do x11 forwarding, but that would just send the remote machine's UI output/desktop to your local machine which might not be what you want. Doing it with x11 forwarding, then you'd run AutoPy locally against the forwarded UI.

One alternative you have would be to use VNC to "see" the remote Ubuntu system. And run the AutoPy script via the VNC session (i.e. local shell within VNC, not remote shell from your local machine).

There are some workarounds for that kind of thing for Windows UI automation for remote desktop protocol (RDP), but I don't know of equivalents for Linux/Ubuntu, best to go the VNC route, which works cross-platform.

Or use my AutoPyDriverServer alternative which would also work, by running a server on the remote machine and connecting to it and driving the mouse via the WebDriver API (wrapper) to AutoPy.
